// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

package pbcodec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 请求头
type S_ReqHeader struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	MethodName           string   `protobuf:"bytes,2,opt,name=MethodName,proto3" json:"MethodName,omitempty"`
	ReqID                uint64   `protobuf:"varint,3,opt,name=ReqID,proto3" json:"ReqID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S_ReqHeader) Reset()         { *m = S_ReqHeader{} }
func (m *S_ReqHeader) String() string { return proto.CompactTextString(m) }
func (*S_ReqHeader) ProtoMessage()    {}
func (*S_ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_header_60c28db0f1185bb8, []int{0}
}
func (m *S_ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S_ReqHeader.Unmarshal(m, b)
}
func (m *S_ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S_ReqHeader.Marshal(b, m, deterministic)
}
func (dst *S_ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S_ReqHeader.Merge(dst, src)
}
func (m *S_ReqHeader) XXX_Size() int {
	return xxx_messageInfo_S_ReqHeader.Size(m)
}
func (m *S_ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_S_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_S_ReqHeader proto.InternalMessageInfo

func (m *S_ReqHeader) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *S_ReqHeader) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *S_ReqHeader) GetReqID() uint64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

// 回复头
type S_RspHeader struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	MethodName           string   `protobuf:"bytes,2,opt,name=MethodName,proto3" json:"MethodName,omitempty"`
	ReqID                uint64   `protobuf:"varint,3,opt,name=ReqID,proto3" json:"ReqID,omitempty"`
	Fail                 string   `protobuf:"bytes,4,opt,name=Fail,proto3" json:"Fail,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S_RspHeader) Reset()         { *m = S_RspHeader{} }
func (m *S_RspHeader) String() string { return proto.CompactTextString(m) }
func (*S_RspHeader) ProtoMessage()    {}
func (*S_RspHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_header_60c28db0f1185bb8, []int{1}
}
func (m *S_RspHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspHeader.Unmarshal(m, b)
}
func (m *S_RspHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspHeader.Marshal(b, m, deterministic)
}
func (dst *S_RspHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspHeader.Merge(dst, src)
}
func (m *S_RspHeader) XXX_Size() int {
	return xxx_messageInfo_RspHeader.Size(m)
}
func (m *S_RspHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RspHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RspHeader proto.InternalMessageInfo

func (m *S_RspHeader) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *S_RspHeader) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *S_RspHeader) GetReqID() uint64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *S_RspHeader) GetFail() string {
	if m != nil {
		return m.Fail
	}
	return ""
}

func (m *S_RspHeader) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*S_ReqHeader)(nil), "pbcodec.S_ReqHeader")
	proto.RegisterType((*S_RspHeader)(nil), "pbcodec.S_RspHeader")
}

func init() { proto.RegisterFile("header.proto", fileDescriptor_header_60c28db0f1185bb8) }

var fileDescriptor_header_60c28db0f1185bb8 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0x4a, 0xce, 0x4f, 0x49,
	0x4d, 0x56, 0x4a, 0xe6, 0xe2, 0x0c, 0x4a, 0x2d, 0xf4, 0x00, 0xcb, 0x09, 0x29, 0x70, 0x71, 0x07,
	0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0xfa, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x21, 0x0b, 0x09, 0xc9, 0x71, 0x71, 0xf9, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x80, 0x15, 0x30,
	0x81, 0x15, 0x20, 0x89, 0x08, 0x89, 0x70, 0xb1, 0x06, 0xa5, 0x16, 0x7a, 0xba, 0x48, 0x30, 0x2b,
	0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x4a, 0xbd, 0x8c, 0x5c, 0x9c, 0x41, 0xc5, 0x05, 0xb4, 0xb5,
	0x45, 0x48, 0x88, 0x8b, 0xc5, 0x2d, 0x31, 0x33, 0x47, 0x82, 0x05, 0xac, 0x1e, 0xcc, 0x06, 0xa9,
	0x74, 0x2d, 0x2a, 0xca, 0x2f, 0x92, 0x60, 0x05, 0x0b, 0x42, 0x38, 0x49, 0x6c, 0xe0, 0x40, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x2e, 0x07, 0x1b, 0x14, 0x01, 0x00, 0x00,
}
